### ISSUE TITLE
Checkbox list of statements

### ISSUE THREAD

**Issue by rebeccafrey** [rebeccafrey/capstone-project#1]
![iPhone 8 story #1](https://user-images.githubusercontent.com/61710830/80804453-7ebedb00-8bb5-11ea-9e45-86c0cb954cc4.png)

## Value statement
As a user
I need statement list with checkboxes
So that I can agree and disagree to them.

## Description
List with 20 statements, checkboxes

## Acceptance criteria
- [x] Toggleable checkbox
- [x] Fixed header

## Tasks
- [x] Create feature branch
- [x] Create header
- [x] Create checkbox  in storybook
- [x] Add component to app
- [x] Add style

## Size
M
