### ISSUE TITLE
Implement database

### ISSUE THREAD

**Issue by rebeccafrey** [rebeccafrey/capstone-project#15]
## Value statement - a requirement, not a solution
As a user
I need to submit my data, and others need to submit theirs, to a database
so that I can see all topics.

## Description
Topic and description are not only stored in localStorage, but also in database, so one can submit and share ideas anonymously and can pull input from others, too.

## Acceptance criteria
- [x] create feature branch
- [x] same look and feel as with localStorage
- [x] has required checkbox to submit to database
- [x] adds data to database
- [x] pulls data from firestore & displays on "/topics" page

## Tasks
- [x] create database (firestore)
- [x] add submit logic
- [x] add fetch logic
- [x] create two dummy inputs

## Size
M
