### ISSUE TITLE
Add text depending on result-range

### ISSUE THREAD

**Issue by rebeccafrey** [rebeccafrey/capstone-project#16]
## Value statement - a requirement, not a solution
As a user
I need more information on my result
so that I can understand it better.

## Description
Additional text on results-page, that is shown, depending on how many checkboxes are selected on the statements-page

## Acceptance criteria
- [x] three different texts shown on results page, depending on how many checkboxes are selected
- [x] ranges: 0-6, 7-13, 14-20

## Tasks
- [x] create feature branch
- [x] write texts
- [x] add logic to display/hide texts according to range

## Size
M
