### ISSUE TITLE
Swipe through topics

### ISSUE THREAD

**Issue by rebeccafrey** [rebeccafrey/capstone-project#17]
## Value statement - a requirement, not a solution
As a user
I need to have a visually appealing way to go through the topics
so that it is more fun

## Description (Text, Scribble, Wireframe, Design)
swiping through topics horizontally

## Acceptance criteria
- [ ] it is possible to swipe through the topics vertically
- [ ] one topic at a time
- [ ] it is visible for the user that one can swipe through

## Tasks
- [ ] implement scroll-snap
- [ ] check if it needs to be implemented on a second page, or can be done below form

## Size
S
