### ISSUE TITLE
Filter option

### ISSUE THREAD

**Issue by rebeccafrey** [rebeccafrey/capstone-project#18]
## Value statement - a requirement, not a solution
As a user
I need to search for words in topics
so that I can see if a specific topic is already exists

## Description (Text, Scribble, Wireframe, Design)
search bar where all results are visible

## Acceptance criteria
- [x] not case sensitive
- [x] search bar above topics

## Tasks
- [x] create feature branch
- [x] add search to topics

## Size
S
