### ISSUE TITLE
Rate option

### ISSUE THREAD

**Issue by rebeccafrey** [rebeccafrey/capstone-project#19]
## Value statement - a requirement, not a solution
As a user
I need rate the topics
so that one can see the most interesting topics rated by the community

## Description
clicking on an icon to mark a topic + counter showing overall number of "likes"

## Acceptance criteria
- [ ] toggelable icon per topic
- [ ] counter displayed next to it
- [ ] counter updates with every toggle (based on database data)

## Tasks
- [ ]  create feature branch
- [ ] chose icon
- [ ] toggle icon function
- [ ] include counter next to icon
- [ ] add counter to database

## Size
(small, medium, large)
