### ISSUE TITLE
Submit button and show result

### ISSUE THREAD

**Issue by rebeccafrey** [rebeccafrey/capstone-project#2]
![iPhone 8 story #2 1](https://user-images.githubusercontent.com/61710830/80804426-69e24780-8bb5-11ea-9f55-5e366dbc8aef.png)
![iPhone 8 story #2 2](https://user-images.githubusercontent.com/61710830/80804427-6a7ade00-8bb5-11ea-92e1-b9cdc59c5848.png)
![iPhone 8 story #2 3](https://user-images.githubusercontent.com/61710830/80804428-6b137480-8bb5-11ea-9117-fab8fe74b95d.png)

## Value statement
As a user
I need a button 
So that I can submit my answers and I don’t have to count myself

## Description
Submit button below list, second page that shows number of checked statements

## Acceptance criteria
- [x] Clicking button redirects to page „/result“
- [x] Do not uncheck checkboxes on submit
- [x] Displays number (#) of checked statements on page „/result“

## Tasks
- [x] Create feature branch
- [x] Add button component to app
- [x] Add Routing
- [x] Add counter function that counts checked statements and display the number on screen
- [x] Add picture with scale (high/20 = intro, low/0 = extra)
- [x] Add style; Animation (color change) so click is visible

## Size
M
