### ISSUE TITLE
Sort topics

### ISSUE THREAD

**Issue by rebeccafrey** [rebeccafrey/capstone-project#20]
## Value statement - a requirement, not a solution
As a user
I need to sort by rating
so that I can see the topics with highest rating

## Description
sort function in a "menu bar"

## Acceptance criteria
- [ ] can sort by highest/lowest rating
- [ ] can sort by newest/oldest entry
- [ ] sort function in menu bar

## Tasks
- [ ] create feature branch
- [ ] add sort function to rating
- [ ] include data/time tag in database
- [ ] sort by highest rating, lowest rating, newest, oldest

## Size
S
