### ISSUE TITLE
toggle topics

### ISSUE THREAD

**Issue by rebeccafrey** [rebeccafrey/capstone-project#21]
## Value statement - a requirement, not a solution
As a user
I need to be able to see more topics at once
so that I can find what I search for quicker

## Description 
topics are collapsable, so only topics are shown unless user decides to see description

## Acceptance criteria
- [x] default: short (only topic visible)
- [x] Toggle between short and extended

## Tasks
- [x]  Add toggle logic
- [x] Arrow down/up

## Size
S
