### ISSUE TITLE
Bookmark

### ISSUE THREAD

**Issue by rebeccafrey** [rebeccafrey/capstone-project#22]
## Value statement - a requirement, not a solution
As a user
I need to mark my favourite topics
so that I don't have to scroll through all

## Description
Bookmark option, toggleable icon next to rating & counter

## Acceptance criteria
- [ ] icon positioned in corner next to rating & counter
- [ ] icon toggleable
- [ ] favourites saved to "favourites", user can switch between "all" and "favourites"
- [ ] if no favourites were selected, the favourites site will display 'You haven’t selected any favourites yet'

## Tasks
- [ ] create feature branch
- [ ] chose icon & add to topic
- [ ] add toggle-logic
- [ ] add small navigation to switch between all and favourites
- [ ] save to localStorage
- [ ] default if no topic was bookmarked

## Size
M
