### ISSUE TITLE
Navbar

### ISSUE THREAD

**Issue by rebeccafrey** [rebeccafrey/capstone-project#3]
![iPhone 8 story #3](https://user-images.githubusercontent.com/61710830/80804467-8aaa9d00-8bb5-11ea-8dfb-112c4d4f23be.png)
##Value statement
As a user
I need some navigation possibility
So that I can go back to the statements page and re-submit

## Description
Nav bar with 2 buttons (footer of page)

## Acceptance criteria
- [x] Button "/statements" leads back to statement list
- [x] Button „/result“ leads to result page and shows last result
- [x] User can re-submit (changed) statement list
- [x] New result is shown in „/result“ page

## Tasks
- [x] Create feature branch
Question: nav button in storybook?
- [x] Create navigation with 2 buttons
- [x] Keep last submitted result in local storage
- [x] Add style, Animation (color change) for button so click is visible

## Size
M
