### ISSUE TITLE
Add about page

### ISSUE THREAD

**Issue by rebeccafrey** [rebeccafrey/capstone-project#30]
## Value statement 
As a first-time user
I need to quickly know about the purpose of the app and how to navigate it, but also get more information if I want to
so that I am not overwhelmed and stop reading, but not lost either.

As a multiple-time user
I need to quickly be able to go where I want to seeing as little text as possible
so that I am not bored and have to scroll as little as possible.

## Description 
New design for Homepage: 1-2 sentences of why, with further information on the about page, plus introduction to navigation pane icons that can be tabbed.

## Acceptance criteria
- [ ] Homepage shows all 4 icons (2 in a row, but all visible at once) with a very short explanation where it will redirect to
- [ ] an About page is linked on the Homepage, which offers more information and recos for further reading
- [ ] text on other sites is shortened, with a link to the about page, where necessary

## Tasks
- [ ] create feature branch
- [ ] Add About page (linked on homepage)
- [ ] rewrite texts
- [ ] include icons (bigger size), 2 in a row, with a short sentence that link to the respective subpages

## Size
S
