### ISSUE TITLE
Animation on result page (scale fill, text fadein)

### ISSUE THREAD

**Issue by rebeccafrey** [rebeccafrey/capstone-project#32]
## Value statement 
As a user
I need nice animations
so that I enjoy using the app

## Description
as a start, adding some animation on result-page: scale-fill according to result, text fading in

## Acceptance criteria
- [ ] scale-fill bottom-up, visible for user
- [ ] scale-fill according to result, changing if number changes

## Tasks
- [ ] create feature branch
- [ ] add animation for scale-fill
- [ ] animate result-text so it fades in from the bottom

## Size
S-M
