### ISSUE TITLE
Swipeable bookmarked topics

### ISSUE THREAD

**Issue by rebeccafrey** [rebeccafrey/capstone-project#35]
## Value statement 
As a particpant
I need an engaging way to go through the topics
so that I am drawn into it

## Description 
swipeable topics for bookmarks page

## Acceptance criteria
- [ ] title and description can be shown on one "slide"
- [ ] swipe per topic
- [ ] bookmark logic still working

## Tasks
- [ ] create feature branch
- [ ] decide for swipe (scroll-snap or React Spring)
- [ ] map through topics to have one "slide" per topic
- [ ] don't break the bookmark logic

## Size
L
