### ISSUE TITLE
Add note-feature to each topic

### ISSUE THREAD

**Issue by rebeccafrey** [rebeccafrey/capstone-project#36]
## Value statement 
As a participant
I need to share my thoughts on topics with everyone
so that they can reflect on it

## Description 
for each topic, possibility to add multiple notes below the description

## Acceptance criteria
- [ ] has form - textarea below each topic (opens upon button-click)
- [ ] is saved in the db

## Tasks
- [ ] create feature branch
- [ ] try out if separate collection makes sense in db
- [ ] add form (textarea only) to each topic

## Size
L
