### ISSUE TITLE
Add topics

### ISSUE THREAD

**Issue by rebeccafrey** [rebeccafrey/capstone-project#4]
![iPhone 8 story #4 1](https://user-images.githubusercontent.com/61710830/80804486-9b5b1300-8bb5-11ea-9655-4f0b1fa6985b.png)
![iPhone 8 story #4 2](https://user-images.githubusercontent.com/61710830/80804487-9bf3a980-8bb5-11ea-8296-8c63037240ab.png)
![iPhone 8 story #4 3](https://user-images.githubusercontent.com/61710830/80804488-9c8c4000-8bb5-11ea-81d9-8e48fa24269a.png)
![iPhone 8 story #4 4](https://user-images.githubusercontent.com/61710830/80804489-9c8c4000-8bb5-11ea-9e78-e6645b8f908d.png)

## Value statement
As a user
I need  a form
So that I can add topics I’d like to discuss with others to see hear their view on things

## Description
Third page with form including submit button to add topic & description that then displays fully it at the bottom of the page, nav bar with third button that leads there 

## Acceptance criteria
- [x] third button in nav bar
- [x] form is found on page „/topics“
- [x] submit button disabled until both input fields are filled
- [x] textfield scrollable
- [x] form reacts on submit
- [x] form is cleared after submit
- [x] input is added directly below form
- [x] no error if the same is entered twice

## Tasks
- [x] Create feature branch
- [x] add form with label and textfield
- [x] add functionality: empty fields & refocus on label on submit
- [x] add functionality: add topic and description to top of list below form
- [x] Create third button in navigation („/topics“)
- [x] Add style, Animation (color change) for button so click is visible

## Size
M
