### ISSUE TITLE
Homepage

### ISSUE THREAD

**Issue by rebeccafrey** [rebeccafrey/capstone-project#5]
![iPhone 8 story #5 1](https://user-images.githubusercontent.com/61710830/80804509-ac0b8900-8bb5-11ea-8874-5d3c81e4dca5.png)
![iPhone 8 story #5 2](https://user-images.githubusercontent.com/61710830/80804511-ad3cb600-8bb5-11ea-8b0c-72da6757eb6a.png)

## Value statement
As a user
I need  a warm welcome
So that I understand why I’m here and what I am about to do

## Description
4 page - first page/home page as introduction to topic and why, including button that redirects to second page (with statements). Includes update for nav bar.

## Acceptance criteria
- [x] fourth button in nav bar
- [x] intro text visible
- [x] button that redirects to „/statements“
- [x] button that redirects to „/topics“
- [x] this page is the home page

## Tasks
- [x] Create feature branch
- [x] Add text
- [x] add button that redirects to „/statements“
- [x] Create button in navigation („/home“)
- [x] Add style; Animation (color change) for button so click is visible

## Size
S
